### ISSUE TITLE
mq property doesn't work with Number type

### ISSUE THREAD

**Issue by santiDotIO** [callmecavs/bricks.js#40]
when setting sizes if mq is a number `640` the breakpoint won't response unless it's a string `640px`. it would help if either it worked with both or documentation clarifies it should be a string and not any.

**Comment by callmecavs** [comment]
@santi6291 looking at the relevant options docs (see [here](https://github.com/callmecavs/bricks.js#sizes)) it says "any unit".  the number `640` is technically unit-less, so that's why it doesn't work.  just about every CSS property I can think of requires a unit - be it `px`, `em`, `rem`, etc - which is why it behaves this way. there are of course a few exceptions (like `z-index`) of course

that being said, I agree this is confusing.  I think a docs update is the best route to go here - happy to merge a PR if you want to open one adjusting the language on the README.  otherwise, i'll get to it when I can.  thanks for raising the issue

**Comment by callmecavs** [comment]
fixed in #41 - thanks to @santi6291
