### ISSUE TITLE
Support infinite scrolling?

### ISSUE THREAD

**Issue by pribeh** [callmecavs/bricks.js#45]
@callmecavs As mentioned here https://github.com/callmecavs/bricks.js/issues/42 I presume the update method could used for adapting brick.js to work with an infinite scrolling lib(?). Have you or anyone tried brick.js with an infinite scrolling lib and had success?

**Comment by callmecavs** [comment]
@pribeh correct. the `update` method is preferred because it will only operate on nodes that have not already been positioned.

if the infinite scroll library has a callback or event that fires after new content has been added, that would be the appropriate time to call `update` using your existing Bricks instance. aside from that, I can't be of much help, as I haven't really used any infinite scrolling libraries

thank you kindly for searching the issues, documentation on the `update` method is [here](https://github.com/callmecavs/bricks.js#update) on the README
