### ISSUE TITLE
Support percentage gutters.

### ISSUE THREAD

**Issue by syropian** [callmecavs/bricks.js#7]
It'd be nice to allow percentage width gutters, as I set my grid items widths as a percentage as well (using a Sass mixin that takes columns, and gutter into account). Any plans to implement this?

**Comment by callmecavs** [comment]
unfortunately percentage based gutters and/or elements would make the grid fluid width, which would require a totally different implementation strategy, and much more aggressive resize handling. there are no plans to implement this as of right now, because of the huge impact it would have on performance. on the bright side though, alternatives exist that address your use case.
